name: smartnote_flutter
description: Receipt OCR with Gemini + Firebase (skeleton)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.4
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env

# --- ICON ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/asset/1024.png
  adaptive_icon_foreground: assets/branding/asset/1024.png
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

# --- SPLASH ---
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/branding/asset/1024.png
  color_dark: "#FFFFFF"
  image_dark: assets/branding/asset/1024.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/branding/asset/1024.png
